// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficRules.Infrastructure.Data;

#nullable disable

namespace TrafficRules.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710112544_InitialSqliteMigration")]
    partial class InitialSqliteMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Дорожні знаки"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Name = "1. Загальні положення"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Name = "2. Обов'язки і права водіїв"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Name = "3. Рух із спецсигналами"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Name = "4. Обов'язки пішоходів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Name = "5. Обов'язки і права пасажирів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Name = "6. Вимоги до велосипедистів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Name = "7. Вимоги до осіб, які керують гужовим транспортом"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Name = "8. Регулювання дорожнього руху"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000009"),
                            Name = "9. Попереджувальні сигнали"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000010"),
                            Name = "10. Початок руху та зміна напрямку"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000011"),
                            Name = "11. Розташування ТЗ на дорозі"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000012"),
                            Name = "12. Швидкість руху"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000013"),
                            Name = "13. Дистанція, інтервал, зустрічний роз'їзд"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000014"),
                            Name = "14. Обгін"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000015"),
                            Name = "15. Зупинка і стоянка"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000016"),
                            Name = "16. Проїзд перехресть"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000017"),
                            Name = "17. Переваги маршрутних ТЗ"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000018"),
                            Name = "18. Проїзд пішохідних переходів і зупинок"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000019"),
                            Name = "19. Користування зовнішніми світловими приладами"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000020"),
                            Name = "20. Рух через залізничні переїзди"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000021"),
                            Name = "21. Перевезення пасажирів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000022"),
                            Name = "22. Перевезення вантажу"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000023"),
                            Name = "23. Буксирування та експлуатація складів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000024"),
                            Name = "24. Навчальна їзда"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000025"),
                            Name = "25. Рух у колонах"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000026"),
                            Name = "26. Рух у житловій та пішохідній зоні"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000027"),
                            Name = "27. Рух по автомагістралях і дорогах для автомобілів"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000028"),
                            Name = "28. Рух по гірських дорогах і на крутих спусках"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000029"),
                            Name = "29. Міжнародний рух"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000030"),
                            Name = "30. Номерні, розпізнавальні знаки"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000031"),
                            Name = "31. Технічний стан ТЗ"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000032"),
                            Name = "32. Окремі питання, що потребують узгодження"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000034"),
                            Name = "34. Дорожня розмітка"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000099"),
                            Name = "Медична допомога"
                        });
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdrRuleReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrafficRules.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrafficRules.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficRules.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrafficRules.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Answer", b =>
                {
                    b.HasOne("TrafficRules.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Question", b =>
                {
                    b.HasOne("TrafficRules.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TrafficRules.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
